[2024-04-15T09:24:22.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T09:24:22.141+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table manual__2024-04-15T09:24:20.042173+00:00 [queued]>
[2024-04-15T09:24:22.150+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table manual__2024-04-15T09:24:20.042173+00:00 [queued]>
[2024-04-15T09:24:22.151+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T09:24:22.167+0000] {taskinstance.py:2327} INFO - Executing <Task(ClickHouseOperator): create_pet_table> on 2024-04-15 09:24:20.042173+00:00
[2024-04-15T09:24:22.172+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=396) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T09:24:22.173+0000] {standard_task_runner.py:63} INFO - Started process 398 to run task
[2024-04-15T09:24:22.173+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_clickhouse_dag', 'create_pet_table', 'manual__2024-04-15T09:24:20.042173+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/test_clickhouse_dag.py', '--cfg-path', '/tmp/tmpr0tk4mz8']
[2024-04-15T09:24:22.175+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask create_pet_table
[2024-04-15T09:24:22.222+0000] {task_command.py:426} INFO - Running <TaskInstance: test_clickhouse_dag.create_pet_table manual__2024-04-15T09:24:20.042173+00:00 [running]> on host 6f78617af605
[2024-04-15T09:24:22.309+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_clickhouse_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T09:24:20.042173+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T09:24:20.042173+00:00'
[2024-04-15T09:24:22.310+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T09:24:22.350+0000] {base.py:84} INFO - Using connection ID 'clickhouse_local_test' for task execution.
[2024-04-15T09:24:22.350+0000] {clickhouse.py:79} INFO - 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id INT NOT NULL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            owner VARCHAR NOT NULL);
          
[2024-04-15T09:24:22.360+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T09:24:22.361+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
           ^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 382, in execute
    rv = self.process_ordinary_query(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 213, in receive_result
    return result.get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
    packet = self.receive_packet()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 62.
DB::Exception: Syntax error: failed at position 79 ('PRIMARY') (line 3, col 33): PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            owner VARCHAR NOT NULL). Expected one of: COMMENT, CODEC, TTL, token, Comma, ClosingRoundBracket. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7ff28e4f8609 in ?
11. __clone @ 0x7ff28e41f293 in ?

[2024-04-15T09:24:22.380+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=test_clickhouse_dag, task_id=create_pet_table, execution_date=20240415T092420, start_date=20240415T092422, end_date=20240415T092422
[2024-04-15T09:24:22.395+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task create_pet_table (Code: 62.
DB::Exception: Syntax error: failed at position 79 ('PRIMARY') (line 3, col 33): PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            owner VARCHAR NOT NULL). Expected one of: COMMENT, CODEC, TTL, token, Comma, ClosingRoundBracket. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7ff28e4f8609 in ?
11. __clone @ 0x7ff28e41f293 in ?
; 398)
[2024-04-15T09:24:22.427+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T09:24:22.455+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T09:24:22.459+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
